// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/features/address/presentation/bloc/address_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app/core/error/failures.dart' as _i6;
import 'package:app/features/address/domain/entities/address.dart' as _i7;
import 'package:app/features/address/domain/repositories/address_repository.dart'
    as _i2;
import 'package:app/features/address/domain/usecases/get_address_by_cep.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddressRepository_0 extends _i1.SmartFake
    implements _i2.AddressRepository {
  _FakeAddressRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAddressByCep].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAddressByCep extends _i1.Mock implements _i4.GetAddressByCep {
  MockGetAddressByCep() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddressRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAddressRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AddressRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Address>> call(String? cep) =>
      (super.noSuchMethod(
            Invocation.method(#call, [cep]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Address>>.value(
              _FakeEither_1<_i6.Failure, _i7.Address>(
                this,
                Invocation.method(#call, [cep]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Address>>);
}
